spring:
  application:
    name: reactive-springboot-crud-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/reactive_db
      auto-index-creation: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.example.reactivecrud: DEBUG
    org.springframework.data.mongodb: DEBUG